[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "lanctl"
version = "0.3.0-beta.2"
description = "CLI de control lógico y físico de infraestructuras LAN"
requires-python = ">=3.10"
dependencies = [
    "colorama>=0.4.6,<1",
    "manuf>=1.1.5,<2",
    "netmiko>=4.4,<5",
    "paramiko>=3.5,<4",
    "cryptography>=44,<46",
    "pyserial>=3.5,<4",
    "pywebview>=6.2.1,<7",
]

[project.scripts]
lanctl = "app.cli:main"
als = "app.cli:main"

[tool.setuptools.packages.find]
include = ["app*"]
