"use strict";

const state={devices:[],selectedId:null,icons:[],projects:[],pluginPanels:[],pluginPanel:null,pluginItems:[],pluginSelected:null};
const $=selector=>document.querySelector(selector);
const columns=["state","icon","ip","latency","cnf","alias","mac","name","vendor","group","protocols","description","lastSeen"];

function applyTheme(theme){Object.entries(theme.tokens||{}).forEach(([n,v])=>document.documentElement.style.setProperty(n,v));Object.entries(theme.components||{}).forEach(([id,tokens])=>document.querySelectorAll(`[data-component-id="${id}"]`).forEach(el=>Object.entries(tokens).forEach(([n,v])=>el.style.setProperty(n,v))));}
function message(text,error=false){const el=$("#status-message");el.textContent=text;el.classList.toggle("error-text",error)}
function setBusy(busy,text="Procesando…"){document.body.classList.toggle("busy",busy);document.body.classList.toggle("scan-running",busy&&text.includes("Escaneando"));document.querySelectorAll("button").forEach(button=>button.disabled=busy);if(busy)message(text)}
async function call(method,...args){const fn=window.pywebview?.api?.[method];if(!fn)throw new Error("La API de LANCTL no está disponible");const response=await fn(...args);if(!response.ok)throw new Error(response.error||"Error desconocido del núcleo");return response}
function relativeDate(value){if(!value)return"Nunca";const date=new Date(value);if(Number.isNaN(date.getTime()))return value;const minutes=Math.max(0,Math.round((Date.now()-date.getTime())/60000));if(minutes<1)return"Ahora";if(minutes<60)return`Hace ${minutes} min`;if(minutes<1440)return`Hace ${Math.round(minutes/60)} h`;return`Hace ${Math.round(minutes/1440)} d`}
function iconFor(id){return state.icons.find(icon=>icon.id===id)||state.icons.find(icon=>icon.id==="device.generic")}
function cnfIcon(value){const span=document.createElement("span");const map={O:["cnf-o","○","Círculo · confirmado"],X:["cnf-x","×","Cruz · desconocido"],S:["cnf-select","","Select · marcado"],F:["cnf-fixed","","Fixed · selección fijada"],"@":["cnf-local","@","Equipo local desde el que se monitoriza la LAN"],"-":["cnf-unrecognized","−","No reconocido"]};const spec=map[value]||map["-"];span.className=`cnf-icon ${spec[0]}`;span.textContent=spec[1];span.title=spec[2];span.setAttribute("aria-label",spec[2]);return span}

function renderInventory(payload){state.devices=payload.devices||[];const summary=payload.summary||{};$("#metric-total").textContent=summary.total||0;$("#metric-active").textContent=summary.active||0;$("#metric-alerts").textContent=summary.alerts||0;$("#metric-switches").textContent=summary.switches||0;$("#row-count").textContent=`${state.devices.length} filas`;const body=$("#device-rows");body.replaceChildren();state.devices.forEach(device=>{const row=document.createElement("tr");row.dataset.deviceId=device.id;if(device.id===state.selectedId)row.classList.add("selected");const values={state:null,icon:null,ip:device.ip||"-",latency:device.responseMs==null?"-":Number(device.responseMs).toFixed(1),cnf:null,alias:device.alias||"-",mac:device.mac||"-",name:device.name||"-",vendor:device.manufacturer||"-",group:device.groups.join(", ")||"-",protocols:device.protocols.join(", ")||"-",description:device.description||"-",lastSeen:relativeDate(device.lastSeen)};columns.forEach(key=>{const cell=document.createElement("td");cell.dataset.column=key;if(key==="state"){const dot=document.createElement("i");if(!device.active)dot.classList.add("warning");cell.append(dot,device.active?"Activo":"No detectado")}else if(key==="icon"){const icon=iconFor(device.iconId);if(icon){const image=document.createElement("img");image.className="device-icon";image.src=icon.data;image.alt=icon.name;cell.append(image)}}else if(key==="cnf")cell.append(cnfIcon(device.cnf));else cell.textContent=values[key];row.append(cell)});row.addEventListener("click",()=>selectDevice(device.id));row.addEventListener("dblclick",()=>showDeviceDetails(device.id));body.append(row)});applyColumnPreferences();$("#empty-devices").hidden=state.devices.length>0;if(state.selectedId){const selected=state.devices.find(device=>device.id===state.selectedId);selected?renderSelected(selected):clearSelected()}else if(state.devices.length)selectDevice(state.devices[0].id)}
function selectDevice(id){state.selectedId=id;document.querySelectorAll("#device-rows tr").forEach(row=>row.classList.toggle("selected",row.dataset.deviceId===id));const device=state.devices.find(item=>item.id===id);if(device){$("#wake-device").disabled=!device.wolAvailable;renderSelected(device)}}
function addDetailField(container,label,value){const box=document.createElement("div"),term=document.createElement("dt"),detail=document.createElement("dd");term.textContent=label;detail.textContent=value||"-";box.append(term,detail);container.append(box)}
async function openService(id,service,port){try{const payload=await call("open_service",id,service,port);message(payload.message)}catch(error){message(error.message,true)}}
async function showDeviceDetails(id=state.selectedId){if(!id)return message("Selecciona un elemento",true);selectDevice(id);const dialog=$("#device-details"),loading=$("#details-loading"),content=$("#details-content");loading.textContent="Inspeccionando servicios y puertos…";loading.classList.remove("error-text");loading.hidden=false;content.hidden=true;dialog.showModal();try{const {device,diagnostic}=await call("get_device_details",id);$("#details-title").textContent=device.alias||device.name||device.ip;const fields=$("#details-fields");fields.replaceChildren();[["Estado",diagnostic.reachable?"Activo":"No detectado"],["IP",device.ip],["MAC",device.mac],["Alias",device.alias],["Nombre",device.name],["Fabricante",device.manufacturer],["CNF",device.cnf],["Grupos",device.groups.join(", ")],["Protocolos",(diagnostic.detected_protocols||device.protocols).join(", ")],["Hostname",diagnostic.hostname],["Latencia",diagnostic.latency_ms==null?"-":`${diagnostic.latency_ms} ms`],["Última detección",device.lastSeen||"Nunca"],["Descripción",device.description],["Tipo identificado",diagnostic.identification?.device_type]].forEach(([label,value])=>addDetailField(fields,label,value));const services=$("#details-services");services.replaceChildren();(diagnostic.open_ports||[]).forEach(port=>{const row=document.createElement("div");row.className="service-row";const number=document.createElement("span"),name=document.createElement("span"),evidence=document.createElement("span");number.className="service-port";number.textContent=`TCP ${port.port}`;name.className="service-name";name.textContent=port.label||port.service.toUpperCase();evidence.className="service-evidence";evidence.textContent=port.product||port.evidence||"Puerto detectado";row.append(number,name,evidence);if(port.interactive){const button=document.createElement("button");button.textContent=port.service==="ssh"?"Abrir terminal":"Abrir";button.addEventListener("click",()=>openService(device.id,port.service,port.port));row.append(button)}services.append(row)});if(!diagnostic.open_ports?.length){const empty=document.createElement("div");empty.className="no-services";empty.textContent="No se detectaron puertos habituales abiertos";services.append(empty)}loading.hidden=true;content.hidden=false}catch(error){loading.textContent=error.message;loading.classList.add("error-text")}}
function renderSelected(device){$("#selected-title").textContent=device.alias||device.name||device.ip;$("#selected-kind").textContent=device.description||"Elemento LAN";$("#selected-ip").textContent=device.ip||"-";$("#selected-mac").textContent=device.mac||"-";$("#selected-vendor").textContent=device.manufacturer||"-";$("#edit-name").value=device.name||"";$("#edit-alias").value=device.alias||"";$("#edit-description").value=device.description==="-"?"":device.description||"";$("#edit-icon").value=device.iconId||"device.generic";const icon=iconFor(device.iconId);$("#selected-icon").src=icon?.data||"";const protocols=$("#selected-protocols");protocols.replaceChildren();if(!device.protocols.length)protocols.textContent="-";device.protocols.forEach(protocol=>{const tag=document.createElement("span");tag.textContent=protocol.toUpperCase();protocols.append(tag," ")});$("#selected-status").classList.toggle("warning",!device.active);$("#diagnostic-output").hidden=true}
function clearSelected(){state.selectedId=null;$("#selected-title").textContent="Ninguno";$("#selected-kind").textContent="Selecciona una fila del inventario"}
async function refresh(query=""){try{renderInventory(await call("list_devices",query));message(`${state.devices.length} elementos mostrados`)}catch(error){message(error.message,true)}}

function renderIcons(){const select=$("#edit-icon");select.replaceChildren();state.icons.forEach(icon=>{const option=document.createElement("option");option.value=icon.id;option.textContent=icon.name;select.append(option)})}
function renderProjects(payload){state.projects=payload.projects||[];const select=$("#project-select");select.replaceChildren(new Option("Sin proyecto",""));state.projects.forEach(project=>select.add(new Option(project.name,project.path)));select.value=payload.activeProject||""}

function setupColumns(){const box=$("#column-options");const saved=JSON.parse(localStorage.getItem("lanctl.columns")||"{}");document.querySelectorAll("th[data-column]").forEach(header=>{const key=header.dataset.column;const label=document.createElement("label");const input=document.createElement("input");input.type="checkbox";input.checked=saved[key]!==false;input.addEventListener("change",()=>{saved[key]=input.checked;localStorage.setItem("lanctl.columns",JSON.stringify(saved));applyColumnPreferences()});label.append(input,header.textContent);box.append(label)})}
function applyColumnPreferences(){const saved=JSON.parse(localStorage.getItem("lanctl.columns")||"{}");columns.forEach(key=>document.querySelectorAll(`[data-column="${key}"]`).forEach(cell=>cell.classList.toggle("column-hidden",saved[key]===false)))}
function resizeColumn(event,header,index){event.preventDefault();const startX=event.clientX,startWidth=header.offsetWidth;const move=e=>{const width=Math.max(45,startWidth+e.clientX-startX);header.style.width=`${width}px`;header.style.minWidth=`${width}px`;localStorage.setItem(`lanctl.width.${columns[index]}`,String(width))};const stop=()=>{window.removeEventListener("pointermove",move);window.removeEventListener("pointerup",stop)};window.addEventListener("pointermove",move);window.addEventListener("pointerup",stop)}
function restoreWidths(){columns.forEach(key=>localStorage.removeItem(`lanctl.width.${key}`))}

async function bootstrap(){try{const payload=await call("bootstrap");applyTheme(payload.theme);state.icons=payload.icons||[];renderIcons();renderProjects(payload);renderPluginNavigation(payload.pluginPanels||[]);document.title=`LANCTL ${payload.version}`;$("#app-version").textContent=payload.version;setupColumns();restoreWidths();renderInventory(payload);message("Inventario conectado al núcleo de LANCTL")}catch(error){message(error.message,true)}}

function renderPluginNavigation(panels){state.pluginPanels=panels;const host=$("#plugin-navigation");host.replaceChildren();panels.sort((a,b)=>(a.order||0)-(b.order||0)).forEach(panel=>{const button=document.createElement("button");button.textContent=panel.title;button.dataset.pluginPanel=panel.id;button.addEventListener("click",()=>showPluginPanel(panel.id,{}));host.append(button)})}
function setView(name){$("#devices-panel").hidden=name!=="devices";$("#plugin-panel").hidden=name!=="plugin";$("#activity-panel").hidden=name!=="activity";document.querySelectorAll(".main-navigation button").forEach(button=>button.classList.toggle("active",button.dataset.panel===name||name==="plugin"&&button.dataset.pluginPanel===state.pluginPanel?.id))}
async function showActivity(){setView("activity");const body=$("#activity-rows");body.replaceChildren();try{const payload=await call("get_history","",{limit:500,reverse:true});const events=payload.events||[];events.forEach(event=>{const row=document.createElement("tr");const device=event.device?.label||event.device?.name||"LAN";[event.timestamp?.slice(0,19)||"-",device,event.type||"-",event.result||"-",event.summary||"-"].forEach(value=>{const cell=document.createElement("td");cell.textContent=value;row.append(cell)});body.append(row)});$("#activity-empty").hidden=events.length>0}catch(error){$("#activity-empty").textContent=error.message;$("#activity-empty").hidden=false}}
async function showPluginPanel(id,context={}){const panel=state.pluginPanels.find(item=>item.id===id);if(!panel)return;state.pluginPanel=panel;setView("plugin");$("#plugin-title").textContent=panel.title;$("#plugin-description").textContent=panel.emptyState?.description||"";renderPluginActions((panel.actions||[]).filter(a=>a.placement==="panel-toolbar"),$("#plugin-toolbar-actions"));try{const payload=await call(panel.owner==="LANCTL"?"monitor_data":"plugin_panel_data",...(panel.owner==="LANCTL"?[]:[id,context]));if(!payload.data.success)throw new Error(payload.data.message);renderPluginData(payload.data.data||{})}catch(error){$("#plugin-empty").textContent=`${error.message}. Puedes reintentar la operación.`;$("#plugin-empty").hidden=false}}
function renderPluginData(data){state.pluginItems=data.items||[];const metrics=$("#plugin-metrics");metrics.replaceChildren();Object.entries(data.metrics||{}).forEach(([key,value])=>{const item=document.createElement("span");item.textContent=`${key}: ${value}`;metrics.append(item)});const columns=state.pluginPanel.columns||[];const head=$("#plugin-head");head.replaceChildren();columns.forEach(column=>{const th=document.createElement("th");th.textContent=column.label||column.field;head.append(th)});renderPluginRows(state.pluginItems)}
function renderPluginRows(items){const body=$("#plugin-rows");body.replaceChildren();const columns=state.pluginPanel.columns||[];items.forEach(item=>{const row=document.createElement("tr");columns.forEach(column=>{const cell=document.createElement("td");cell.textContent=item[column.field]??"-";row.append(cell)});row.addEventListener("click",()=>{state.pluginSelected=item;document.querySelectorAll("#plugin-rows tr").forEach(x=>x.classList.remove("selected"));row.classList.add("selected");renderPluginDetail(item)});body.append(row)});const empty=$("#plugin-empty");empty.textContent=state.pluginPanel.emptyState?.description||"No hay datos";empty.hidden=items.length>0}
function renderPluginDetail(item){const detail=$("#plugin-detail");detail.replaceChildren();const title=document.createElement("h2");title.textContent=item.name||item.server||"Recurso";detail.append(title);const list=document.createElement("dl");[["Tipo",item.type],["Ruta",item.path],["Estado",item.state],["Servidor",item.server],["Acceso",item.access]].forEach(([label,value])=>{const box=document.createElement("div"),dt=document.createElement("dt"),dd=document.createElement("dd");dt.textContent=label;dd.textContent=value||"-";box.append(dt,dd);list.append(box)});detail.append(list);const server=document.createElement("button");server.textContent="Ver servidor";server.addEventListener("click",showResourceServer);detail.append(server);renderPluginActions(state.pluginPanel.actions.filter(a=>a.placement==="detail"),detail)}
function showResourceServer(){const id=state.pluginSelected?.deviceId;if(!id)return;setView("devices");selectDevice(id);document.querySelector(`tr[data-device-id="${id}"]`)?.scrollIntoView({block:"center"})}
function renderPluginActions(actions,host){host.querySelectorAll("button").forEach(button=>button.remove());actions.forEach(action=>{const button=document.createElement("button");button.textContent=action.label;button.addEventListener("click",async()=>{const confirmed=!action.confirmation||confirm(action.confirmation);if(!confirmed)return;try{const payload=await call("plugin_action",action.id,{itemId:state.pluginSelected?.id,confirmed});message(payload.result.message||"Acción completada",!payload.result.success);if(action.id.includes("scan"))await showPluginPanel(state.pluginPanel.id,{})}catch(error){message(error.message,true)}});host.append(button)})}
$("#plugin-search").addEventListener("input",event=>{const query=event.target.value.toLocaleLowerCase();renderPluginRows(state.pluginItems.filter(item=>Object.values(item).some(value=>typeof value==="string"&&value.toLocaleLowerCase().includes(query))))});document.querySelectorAll(".main-navigation button[data-panel]").forEach(button=>button.addEventListener("click",()=>button.dataset.panel==="activity"?showActivity():setView(button.dataset.panel)));

$("#refresh-devices").addEventListener("click",()=>refresh($("#device-search").value));let searchTimer;$("#device-search").addEventListener("input",event=>{clearTimeout(searchTimer);searchTimer=setTimeout(()=>refresh(event.target.value),180)});
$("#scan-network").addEventListener("click",async()=>{if(!confirm("¿Iniciar un escaneo normal de la red autorizada?"))return;setBusy(true,"Escaneando la red LAN…");try{const payload=await call("scan_network","normal");renderInventory(payload);message(payload.message)}catch(error){message(error.message,true)}finally{setBusy(false)}});
$("#save-device").addEventListener("click",async()=>{if(!state.selectedId)return message("Selecciona un elemento",true);setBusy(true,"Guardando cambios…");try{const payload=await call("update_device",state.selectedId,{name:$("#edit-name").value,alias:$("#edit-alias").value,description:$("#edit-description").value,icon:$("#edit-icon").value});renderInventory(payload);message("Elemento actualizado")}catch(error){message(error.message,true)}finally{setBusy(false)}});
$("#diagnose-device").addEventListener("click",async()=>{if(!state.selectedId)return message("Selecciona un elemento",true);setBusy(true,"Diagnosticando y detectando protocolos…");try{const {diagnostic}=await call("diagnose_device",state.selectedId);const ports=diagnostic.open_ports.map(port=>`${port.port}/${port.service}${port.product?` · ${port.product}`:""}`).join("\n")||"Ningún puerto habitual abierto";const output=$("#diagnostic-output");output.textContent=`${diagnostic.reachable?"ACTIVO":"NO DETECTADO"}\nLatencia: ${diagnostic.latency_ms??"-"} ms\nHostname: ${diagnostic.hostname||"-"}\nProtocolos: ${(diagnostic.detected_protocols||[]).join(", ")||"-"}\n\n${ports}`;output.hidden=false;await refresh($("#device-search").value);message("Diagnóstico y protocolos actualizados")}catch(error){message(error.message,true)}finally{setBusy(false)}});
$("#show-details").addEventListener("click",()=>showDeviceDetails());
$("#show-shares").addEventListener("click",()=>{const panel=state.pluginPanels.find(item=>item.id==="windows-smb.resources");if(panel)showPluginPanel(panel.id,{deviceId:state.selectedId});else message("Activa Windows SMB Discovery para ver recursos compartidos",true)});
$("#close-details").addEventListener("click",()=>$("#device-details").close());
$("#device-details").addEventListener("click",event=>{if(event.target===$("#device-details"))$("#device-details").close()});
$("#open-terminal").addEventListener("click",async()=>{if(!state.selectedId)return message("Selecciona un elemento",true);try{const payload=await call("open_terminal",state.selectedId);message(payload.message)}catch(error){message(error.message,true)}});
$("#wake-device").addEventListener("click",async()=>{if(!state.selectedId)return message("Selecciona un elemento",true);setBusy(true,"Enviando señal de encendido…");try{message("Esperando a que el equipo responda…");const payload=await call("wake_device",state.selectedId,{});message(payload.message,payload.result?.status==="timeout")}catch(error){message(error.message,true)}finally{setBusy(false)}});
$("#open-device").addEventListener("click",async()=>{if(!state.selectedId)return message("Selecciona un elemento",true);const device=state.devices.find(item=>item.id===state.selectedId);const protocol=device.protocols.includes("https")?"https":device.protocols.includes("http")?"http":"auto";try{const payload=await call("open_device",state.selectedId,protocol);message(payload.message)}catch(error){message(error.message,true)}});
$("#project-select").addEventListener("change",async event=>{if(!event.target.value)return;setBusy(true,"Cargando proyecto…");try{const payload=await call("use_project",event.target.value);renderProjects(payload);message(payload.message)}catch(error){message(error.message,true)}finally{setBusy(false)}});
$("#project-open").addEventListener("click",async()=>{try{const selected=await call("select_project_file");if(!selected.path)return;setBusy(true,"Cargando proyecto…");const payload=await call("use_project",selected.path);renderProjects(payload);message(payload.message)}catch(error){message(error.message,true)}finally{setBusy(false)}});
$("#activity-refresh").addEventListener("click",showActivity);
$("#project-save").addEventListener("click",async()=>{setBusy(true,"Guardando proyecto…");try{const payload=await call("save_project");renderProjects(payload);message(payload.message)}catch(error){message(error.message,true)}finally{setBusy(false)}});
$("#project-new").addEventListener("click",async()=>{const name=prompt("Nombre del nuevo proyecto:");if(!name)return;try{const selected=await call("select_project_directory");if(!selected.path)return;setBusy(true,"Creando proyecto…");const payload=await call("create_project",name,selected.path);renderProjects(payload);message(payload.message)}catch(error){message(error.message,true)}finally{setBusy(false)}});
document.addEventListener("keydown",event=>{if(!["ArrowUp","ArrowDown"].includes(event.key)||["INPUT","SELECT","TEXTAREA"].includes(document.activeElement?.tagName))return;if(!state.devices.length)return;event.preventDefault();const current=Math.max(0,state.devices.findIndex(device=>device.id===state.selectedId));const next=event.key==="ArrowDown"?Math.min(state.devices.length-1,current+1):Math.max(0,current-1);selectDevice(state.devices[next].id);document.querySelector(`tr[data-device-id="${state.devices[next].id}"]`)?.scrollIntoView({block:"nearest"})});
window.addEventListener("pywebviewready",bootstrap);
