[platformio]
default_envs = blackpill_f411ce

[env:blackpill_f411ce]
platform = ststm32
board = genericSTM32F411CE
framework = arduino
upload_protocol = stlink
monitor_port = COM50
monitor_speed = 115200
lib_deps =
    jandrassy/EthernetENC@^2.0.5
    wolfssl/Arduino-wolfSSL@5.7.2
    https://github.com/wolfSSL/wolfssh.git#v1.5.0-stable
    paulstoffregen/OneWire@^2.3.8
    milesburton/DallasTemperature@^4.0.6
    adafruit/Adafruit NeoPixel@^1.15.1
build_flags =
    -I.pio/libdeps/blackpill_f411ce/wolfssh
    -D PIO_FRAMEWORK_ARDUINO_ENABLE_CDC
    -D USBCON
    -D HAL_PCD_MODULE_ENABLED
    -D SERIAL_USB
    -D SSH_PORT=22
    -D SSH_USERNAME=\"admin\"
    -D SSH_PASSWORD=\"CHANGE_ME_BEFORE_FLASHING\"
    -D WOLFSSL_USER_SETTINGS
    -D WOLFSSL_WOLFSSH
    -D WOLFSSL_SERVER_EXAMPLE
    -D WOLFSSL_SHA512
    -D WOLFSSH_SMALL_STACK
    -D WOLFSSH_NO_FILESYSTEM
    -D WOLFSSH_USER_IO
    -D WS_NO_SIGNAL
